# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('seoul', '서울'), ('gyunggi', '경기'), ('incheon', '인천'), ('busan', '부산'), ('gwangju', '광주'), ('daejeon', '대전')], default='seoul', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('food', '맛집'), ('cafe', '카페'), ('drink', '술집'), ('shopping', '쇼핑'), ('karaoke', '노래방'), ('gallery', '문화생활'), ('beauty', '뷰티/헤어/네일')], default='food', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_rating', models.PositiveSmallIntegerField()),
                ('content', models.TextField(blank=True)),
                ('n_like', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=80)),
                ('intro', models.TextField(blank=True, max_length=500)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('tel', models.CharField(blank=True, max_length=20)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('hours', models.CharField(blank=True, max_length=20)),
                ('store_rating', models.FloatField(blank=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.Area')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.Category')),
            ],
        ),
        migrations.CreateModel(
            name='SubArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hongdae', '홍대/신촌'), ('hoegi', '회기/강북'), ('gyodae', '교대/강남'), ('sinlim', '신림'), ('sadang', '사당이수'), ('itaewon', '이태원용산'), ('guro', '구로/영등포'), ('jongro', '종로/명동'), ('jamsil', '잠실/송파'), ('gundae', '건대/강변')], default='hongdae', max_length=20)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.Area')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('chicken', '치킨'), ('pizza', '피자'), ('korean', '한식'), ('snack', '분식'), ('japanese', '일식'), ('chinese', '중식'), ('meat', '고기'), ('fastfood', '패스트푸드'), ('soju', '소주'), ('beer', '맥주'), ('cocktail', '칵테일'), ('liquor', '양주'), ('sake', '사케/이자까야'), ('makgoli', '막걸리')], default='pizza', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('nickname', models.CharField(max_length=20)),
                ('n_review', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('intro', models.TextField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interest', models.BooleanField()),
                ('n_following', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('n_follower', models.PositiveSmallIntegerField(blank=True, default=0)),
                ('profile', models.ImageField(blank=True, upload_to='')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.Area')),
                ('sub_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.SubArea')),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='sub_area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.SubArea'),
        ),
        migrations.AddField(
            model_name='store',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.SubCategory'),
        ),
        migrations.AddField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.User'),
        ),
        migrations.AddField(
            model_name='review',
            name='review_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.Store'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='legolas.Review'),
        ),
    ]
