# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legolas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(to='legolas.Category'),
        ),
        migrations.RemoveField(
            model_name='store',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='store',
            name='sub_category',
            field=models.ManyToManyField(to='legolas.SubCategory'),
        ),
    ]
