# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('legolas', '0002_auto_20160119_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='legolas.Category'),
            preserve_default=False,
        ),
    ]
